version: '3.3'
services:
  app:
    container_name: biogw-metadb-dev
    restart: always
    build: node_modules
    ports:
    - 3002:3001
    - 9229:9229
    command:
      - npm
      - "run"
      - "start"
    volumes:
    - ./:/app
  mongo:
    container_name: biogw-metadb-mongo-dev
    image: mongo
    expose:
    - 27017
    volumes:
    - ./db-dev:/data/db
volumes:
  dscor-data:
