version: '3.3'
services:
  app:
    container_name: biogw-metadb-prod
    restart: always
    build: .
    ports:
    - 3001:3001
    - 9229:9229
    command:
      - npm
      - "run"
      - "start"
    volumes:
    - ./:/app
  mongo:
    container_name: biogw-metadb-mongo
    image: mongo
    expose:
    - 27017
    ports:
      - 27027:27017
    volumes:
    - ./db:/data/db
volumes:
  dscor-data:
