version: '3.3'
services:
  app:
    depends_on:
      - mongo
    restart: always
    build: .
    ports:
    - 3002:3001
    command:
      - npm
      - "run"
      - "start"
    volumes:
    - ./:/app
  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
    - ./db:/data/db
