version: '3.3'
services:
  app:
    container_name: dscor-server
    restart: always
    build: src
    ports:
    - 3001:3001
    - 9229:9229
    command:
      - npm
      - "run"
      - "debug"
    volumes:
    - ./:/app
  mongo:
    container_name: dscor-mongo-db
    image: mongo
    expose:
    - 27017
    volumes:
    - ./db:/data/db
volumes:
  dscor-data:
